/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpcomingRouteImport } from './routes/upcoming'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TvTmdbIdRouteImport } from './routes/tv/$tmdbId'
import { Route as MovieTmdbIdRouteImport } from './routes/movie/$tmdbId'

const UpcomingRoute = UpcomingRouteImport.update({
  id: '/upcoming',
  path: '/upcoming',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TvTmdbIdRoute = TvTmdbIdRouteImport.update({
  id: '/tv/$tmdbId',
  path: '/tv/$tmdbId',
  getParentRoute: () => rootRouteImport,
} as any)
const MovieTmdbIdRoute = MovieTmdbIdRouteImport.update({
  id: '/movie/$tmdbId',
  path: '/movie/$tmdbId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/profile': typeof ProfileRoute
  '/upcoming': typeof UpcomingRoute
  '/movie/$tmdbId': typeof MovieTmdbIdRoute
  '/tv/$tmdbId': typeof TvTmdbIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/profile': typeof ProfileRoute
  '/upcoming': typeof UpcomingRoute
  '/movie/$tmdbId': typeof MovieTmdbIdRoute
  '/tv/$tmdbId': typeof TvTmdbIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/profile': typeof ProfileRoute
  '/upcoming': typeof UpcomingRoute
  '/movie/$tmdbId': typeof MovieTmdbIdRoute
  '/tv/$tmdbId': typeof TvTmdbIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explore'
    | '/profile'
    | '/upcoming'
    | '/movie/$tmdbId'
    | '/tv/$tmdbId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/explore'
    | '/profile'
    | '/upcoming'
    | '/movie/$tmdbId'
    | '/tv/$tmdbId'
  id:
    | '__root__'
    | '/'
    | '/explore'
    | '/profile'
    | '/upcoming'
    | '/movie/$tmdbId'
    | '/tv/$tmdbId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExploreRoute: typeof ExploreRoute
  ProfileRoute: typeof ProfileRoute
  UpcomingRoute: typeof UpcomingRoute
  MovieTmdbIdRoute: typeof MovieTmdbIdRoute
  TvTmdbIdRoute: typeof TvTmdbIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upcoming': {
      id: '/upcoming'
      path: '/upcoming'
      fullPath: '/upcoming'
      preLoaderRoute: typeof UpcomingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv/$tmdbId': {
      id: '/tv/$tmdbId'
      path: '/tv/$tmdbId'
      fullPath: '/tv/$tmdbId'
      preLoaderRoute: typeof TvTmdbIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movie/$tmdbId': {
      id: '/movie/$tmdbId'
      path: '/movie/$tmdbId'
      fullPath: '/movie/$tmdbId'
      preLoaderRoute: typeof MovieTmdbIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExploreRoute: ExploreRoute,
  ProfileRoute: ProfileRoute,
  UpcomingRoute: UpcomingRoute,
  MovieTmdbIdRoute: MovieTmdbIdRoute,
  TvTmdbIdRoute: TvTmdbIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
